
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "01:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "npm"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "01:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "github-action"