version: '3.8'
services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGODB_DATABASE: ack
      MONGODB_ROOT_PASSWORD: password123
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb_master_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  mongodb_master_data:
    driver: local


